language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - rbx
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: rbx

